name: Android • Build & Distribute (Firebase)

on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  build-distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3

      - name: Flutter pub get
        run: flutter pub get

      # (Optional) Signing: only if you added keystore secrets
      - name: Prepare keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/keystore.jks
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_ALIAS_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: devs   # make sure this tester group exists in Firebase
          file: build/app/outputs/bundle/release/app-release.aab
          releaseNotes: "Build ${{ github.sha }} from ${{ github.ref_name }}"
