name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.3"
          cache: true

      - name: Install Android SDK 35 + build-tools
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: pub-${{ runner.os }}-

      - name: Remove KTS duplicates if present
        run: |
          rm -f android/settings.gradle.kts || true
          rm -f android/app/build.gradle.kts || true

      - name: Ensure Android wrapper exists
        run: |
          if [ ! -f android/gradlew ]; then
            flutter create . --platforms=android --project-name autocare_pro
          fi
          chmod +x android/gradlew

      # ---- Provision signing (writes to android/app/, writes a clean key.properties) ----
      - name: Provision Android keystore & key.properties
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${ANDROID_KEYSTORE_PASSWORD}" >> android/key.properties
          echo "keyAlias=${ANDROID_KEY_ALIAS}" >> android/key.properties
          echo "keyPassword=${ANDROID_KEY_ALIAS_PASSWORD}" >> android/key.properties
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Pub get (resolve deps)
        run: flutter pub get

      - name: Verify signing files
        run: |
          ls -l android/app
          sed -n '1,50p' android/key.properties | sed -E 's/(password=).*/\1****/g'

      - name: keytool sanity check
        run: |
          keytool -list -v -keystore android/app/upload-keystore.jks -alias "$ANDROID_KEY_ALIAS" -storepass "$ANDROID_KEYSTORE_PASSWORD" >/dev/null
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

      # ---- Build using Gradle directly so we always get the real stacktrace ----
      - name: Gradle assembleRelease (with stacktrace)
        run: |
          cd android
          ./gradlew clean
          # Full logs to a file + console
          ./gradlew :app:assembleRelease --no-daemon --stacktrace --info --warning-mode all | tee ../gradle-build.log
          cd ..
        shell: bash

      - name: Upload Gradle log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: gradle-build.log

      # ---- Copy APK to standard Flutter path for the next steps (in case paths differ) ----
      - name: Locate APK and normalize path
        run: |
          set -e
          APK_PATH=$(find android/app/build/outputs -type f -name "app-release*.apk" | head -n 1)
          echo "Found APK: $APK_PATH"
          mkdir -p build/app/outputs/flutter-apk
          cp "$APK_PATH" build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Firebase App Distribution (Android)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          testers: "ahmerparacha2016@gmail.com"
          releaseNotes: "CI build ${{ github.run_number }} from ${{ github.sha }}"
          debug: true