name: Android • Build & Distribute (Firebase)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: devs
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Build ${{ github.sha }} from ${{ github.ref_name }}"